version: "3.8"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: web
    command: /start
    volumes:
      - .:/app
      # - web_static_volume:/app/static
    expose:
      - 8000

  # volumes:
  #   web_static_volume:
